[package]
name = "kohaku"
version = "0.1.3"
edition = "2024"
description = "A simple tokenizer"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mushitoriami/kohaku"

[dependencies]
